### ISSUE TITLE
MQTT Username/Password

### ISSUE THREAD

**Issue by camwise** [mzac/unifi-video-mqtt#1]
Sorry for the Newb question, but I am using Cloudmqtt.  How would i include the port, username, and password in the script you provided for the MQTT broker?

**Comment by camwise** [comment]
Sorry my bad.  I just googled the mosquitto_pub command and found all the variables I needed to pass.  Works great by the way!  Crazy precise and fast on detecting motion.

**Comment by mzac** [comment]
Thanks! I'll see about modifying the script anyways to include options for user/password and maybe other options too.

**Comment by mzac** [comment]
Added in cb4d9dd6748ae71102b100ed87c983773da42acc
