### ISSUE TITLE
Is this still working

### ISSUE THREAD

**Issue by wranglatang** [mzac/unifi-video-mqtt#9]
Hi There,

Is this still working with the latest version of Unifi Video? I have managed to set it up in UNRAID and its able to watch the log, but it doesn't seem to trigger. any idea why? I just says this:
`Setting up watches.
Watches established.`

**Comment by mzac** [comment]
Good question.  I haven't been using Unifi Video for a while now that I got a cloud key plus and I'm using Unifi Protect.
